apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  repositories: |
    - url: https://dskudney/argoflow
      passwordSecret:
        name: git-repo-secret
        key: HTTPS_PASSWORD
      usernameSecret:
        name: git-repo-secret
        key: HTTPS_USERNAME
