kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgCjWgr+pPCmuW6napX5qBa+ymhvUlY3Zx9kaiBej4T19EemH1Eu3b2aX9NXNfsz/dGkUMp0yXdFMLt4+miiBkpllgVjbsYI6LIIEltlBEoJN15ISLrq2YxGGvr2CYZ/zigpTuJCNY+USr5axSkgOU1/Rbvbad6nni8J9b2ofV2oXq2ansS0q9+8/+2GTA6HFWaHCNPMQ/OGWFXD5WgRaprCjT/mqGXvircG/uH9zn2GdvgOdi6rr5djJ/Fxb9d88VJUEFQfza2US+n1CuiikzVYERztz3t9VGzq85x4q8S8sHC921m7PRhhsJgaUY64oLvLfpFwTgAYPOc7x6QFgqG1jBHuhmAaDbd8wO6wKZa2NSl373uia+nfTxbPyzrUfZg9I3hsdPfaxKE4XKGLDJ3MtlK+v6FhKPbh5pUVC/xyq2zrlYlyX+hf+5+dh5FO24UMWcsXozux5VVGKr0NgMlPWalFFRJKK09ceJ66w6q/UOHihNSN1FbX8K+gGDrvvosdbWOGtznPKxUuRCnE6F7uIb6IJByhBUORo8sAbs5JoLXX8D4jAYKUBSjoDfPNRKaeb9TCgFHZOOu5wLIqjxKopH9wIdAxa2ZiS1e6qicWqoyLT/OqCIPs+nkyNktH4kPHWRJ5OM83i8iwVB0KOfGcW6aliTSf9IhRjohKiW5U55g7oMdfimooUL9jDmJ02bbqaT8Z
    admin-user: AgBJF72LZbB4WGfeJj2qBUmdPAeaGGfjoTPBXiU7rUUuj3w46MD3XoFgzQGjRx8rjHdAI54CEennRQU3fXHiw+hYIrVo8J2jCqeP/5zAgh2JQoCZJexHYQnE5zHwrrnw+PSz17FSbTiKZo3s2ZeMwX6x3hEN1rddt7NH7YgvECwFwKqukykQ+MLtZIUn6jRnHB0OSEpXZTZ9EWsnf2EO6DMp0p5f/K7UXdILZbQWfB6/VCqikIlOU+i9qtCQIkTM8tGZD6YrSk1Btc6JE/tif5H5SdJsz2ZYa2Mb5Kj4R5QZnZX/5e4k+SDYyazQ/A5aq+D5CseNMCtNc3LosDsua06VhflMdSo3wIhHhS3wW+9kWW0cWIzcqfokUdSSTkL8kGs0ydTyJJ4cCAd2g4zFR4dGy0bhuxvAmXEpqzEI4dWUfnDxcRCTGKAdLr1qqlPALHhbUsELOr/ViiP4o42ubm1MUGzA6FDsKJVWBXjaA+8ug6UlaYCIDwCVpHhdyi/ahn5v+Gqr729HWK1O1Ge82f/HeA2kuODxjok4zTnnKJ4ZDxmkPxdAgT43iK3hzXlLeA40k/X5sl9DAhVObbafUxZRvVLc3Hk67u35Dnt2gMF5IInfujN+zSLxXHC4yISV7sH3wygxS/PBlTtqcb3jEtVdfdaTkZEsWpk/th1bn7FvTL0piQZjHUOByXdYKaAOXXjX1itn
